proton: ServiceSpec
pipeline:
  service_dir: ecs-static-website
  dockerfile: Dockerfile
  unit_test_command: echo 'add your unit test command here'
instances:
  - name: load-balanced-fargate-svc-dev
    environment: icici-poc-dev
